name: explain-instance
version: 0.1.0
synopsis: Clever TH hack to explain type constraints
maintainer: Michael Sloan <mgsloan@gmail.com>
license: MIT
github: mgsloan/explain-instance

ghc-options: -Wall -fwarn-tabs -fwarn-incomplete-uni-patterns -fwarn-incomplete-record-updates

dependencies:
  - base >=4.7 && < 5
  - containers
  - syb
  - template-haskell >= 2.11
  - th-reify-many
  - th-expand-syns

library:
  source-dirs: src

tests:
  explain-instance-test:
    source-dirs:
      - test
    dependencies:
      - directory
      - filepath
      - lens
      - typed-process
    main: Spec.hs
